### PR TITLE
update js to ttrss v18.12 (fca78f7) and improvements

### LINKED ISSUE #4: Wrong path for images
Hi,

I just installed the YOURLS plugin and it works just fine ... exept the images of tweetshare and fbshare aren't displayed properly.
image
They are stored in the plugin-directory, but the call in the code ist not goint there.

https://short.domain.tld/plugins/yourls/tweetshare.png <-- in the code (/plugins/yourls/tweetshare.png, to be exactly :) )
https://short.domain.tld/tt-rss/plugins/yourls/tweetshare.png <- actual path

Somehow, the path to the directory of the plugin is not read properly.

Greets, Gabba

### PR DESCRIPTION
**Pull request by joshp23**
Bugfix
-  update js to ttrss v18.12 (fca78f7)  
-  update from legacy db_connect
-  fixes #4 (installation instruction to correct directory + hard-coded paths in js)  

Enhancement
-  add keyboard shortcut "s+y"
-  add material link icon to pref tab
-  make facebook and twitter shares https
-  switch to semantic versioning
-  tidy code

### CODE REVIEW

**Comment by acaranta** [comment]
thx @joshp23 for your contribution ... I admit I merged without checking, as I don't operate anymore any TTRSS or Yourls ... 

on that matter, would you be interested to get ownership for the current repository ? ^^

**Comment by joshp23** [comment]
@acaranta indeed. I assure you, these patches work well :) At least they do against my own installations.

On the other matter, I would be happy to get ownership and continue maintenance.

**Comment by acaranta** [comment]
ah ... first you nedd to delete your fork of this repo, there is a conflict with the name ^^

**Comment by joshp23** [comment]
Wondering if you were still planning on transferring?

**Pull request merged**
